[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "utils"
version = "0.1.0"
description = "Collection of utility functions for image processing, computer vision and deep learning models."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Andrea D'Amicis", email = "andrea.damicis2001@gmail.com" }
]
keywords = ["computer-vision", "image-processing", "opencv", "torch", "augmentation", "python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

# Main dependencies
dependencies = [
    "numpy",
    "opencv-python",
    "matplotlib",
    "pandas",
    "scikit-learn",
    "scipy",
    "seaborn",
    "torch",
    "torchvision",
    "timm",
    "onnxruntime-gpu",
    "ultralytics",
    "Pillow",
    "PyYAML",
    "requests"
]

# Optional dependencies
[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "flake8",
    "mypy"
]

# Entry points
# [project.scripts]
# utils-cli = "utils.cli:main"  # esempio se aggiungi un file cli.py con funzione main()

# Command to install
# pip install --config-settings editable_mode=compat -e .
